### PR TITLE
Generic Object & Data Injection Integration, Warn Popup Visibility - …

### PR DESCRIPTION
**Pull request by maunat**
…Dropdown /front

- Impl. Dropdown to choose whenever to show the warning popup with the highlighted error message
- Impl. to support Generic Object Plugin
- Impl. to support external call to check Statecheck rules on assets (for example, Data Injection can call this hook to check rules during massive import)

### CODE REVIEW

**Comment by ericferon** [comment]
Hi,
Thank you for your contribution !
K.r,
Eric

**Comment by ericferon** [comment]
But I think that modifications to the file inc/rule.class.php are missing, a.o in showForm and rawSearchOptions, in order to add the field 'is_active_warn_popup'.
The file sql/empty-1.0.2.sql is also missing.
You should also add a file sql/update-1.0.2.sql, in order to update the DB schema and add the field 'is_active_warn_popup' to the table 'glpi_plugin_statecheck_rules'.
K.r,

**Comment by maunat** [comment]
Hi Eric,

You are right!

I've pulled a new request right now to include that feature!
Thank you.


M

Il giorno mar 10 ott 2023 alle ore 17:59 Eric Feron <
***@***.***> ha scritto:

**Comment by ericferon** [comment]
Hi,
Can you explain how you did the link between the statecheck plugin and the datainjection one ?
It seems to me that 2 code snippets are important, in setup.php and hook.php : 

- one to link the function plugin_datainjection_populate_statecheck to datainjection
 if (class_exists('PluginStatecheckRule_Item')) { // only if plugin activated
   $PLUGIN_HOOKS['plugin_datainjection_populate']['statecheck'] = 'plugin_datainjection_populate_statecheck';

- the other one, in the plugin_datainjection_populate_statecheck function
   $INJECTABLE_TYPES['PluginStatecheckRuleInjection'] = 'statecheck';

In these snippets, 2 classes are mentioned : PluginStatecheckRule_Item and PluginStatecheckRuleInjection.

1. Where do they come from ? They aren't defined in statecheck plugin.
2. In INJECTABLE_TYPES, most definitions (as in datainjection/setup.php, function getTypesToInject) are associated with 'datainjection'. Which is the meaning of 'statecheck' for 'PluginStatecheckRuleInjection', instead of 'datainjection' for most of other ones ?
K.r,

**Comment by maunat** [comment]
Hi Eric,

That's not my code.

What I did was to add a custom hook into statecheck and then to recall it
from Data Injection Plugin through Plugin::doHook(...).

That's all.

It works well, in fact I am actually able to get the result of Statecheck
Plug-in (a string note with all the rules fired but not respected) as the
last column into the error CSV output of the Data Injection Plug-in.

If you want I can provide you a flow diagram and an example of the output.

Best regards,

Maurizio



Il gio 12 ott 2023, 21:50 Eric Feron ***@***.***> ha scritto:

**Comment by maunat** [comment]
Anyway,

I anticipate you, I potentially need to reorganize the code again because
I've the need to add another feature to this plugin.

This time, probably, I think it's better to put into a private method the
core logic of your checks and then call it from different hooks (i.e. from
the front part, from the external one, and from the new feature) instead to
copy it for the third time.

Hope you appreciate my efforts.

M

Il gio 12 ott 2023, 22:34 Maurizio Natalia ***@***.***> ha
scritto:

**Pull request merged**
